### ISSUE TITLE
1.20.1 Update has broken custom entity textures

### ISSUE THREAD

**Issue by Zanklev** [ObliviousSpartan/SpartanShields#2]
On forge 1.20.1 zombie and spider entities with a custom texture from any texture pack is appearing either invisible or fully black while this mod is installed. So far villagers seem fine with my texture packs. Using Entity Texture Features and "Blue's Better Monsters" and also tested "Tissou's Zombie Pack".

**Comment by ObliviousSpartan** [comment]
Thanks for the report.
I suspect this issue is related to this one (#3) and once the fix for that is installed, it should fix this one too.
Let me know if that's the case so I can close this issue.

**Comment by Zanklev** [comment]
Unfortunately it's still broken, here's a screenshot of what it looks like. I placed six zombies down within the fences.
![runtim Screenshot 2024 06 18 - 08 19 13 65](https://github.com/ObliviousSpartan/SpartanShields/assets/139833714/402e9c10-9c03-442c-b079-784e08d36318)

**Comment by ObliviousSpartan** [comment]
I've tested with the mods and resource packs that you have suggested, and I can't seem to replicate the issue.
I thought at first that the mod "Entity Model Features" was missing since I was using the "Blue's Better Monsters" resource pack and it said it needed that mod. Not the problem.
Is it possible that there is another mod that could be causing a conflict? Can you send me a list of mods that you are getting this problem with? It's possible incompatibility with another mod is causing this issue.

**Comment by Zanklev** [comment]
Man it's gonna be hard to figure it out, I have a modpack of 250+ mods atm. I do remember a certain point where there started being some texture issues so I will go back and check through some of those mods and if I find it I will comment here what it is so it's known what mod combined with this is breaking the textures.

**Comment by Zanklev** [comment]
So eventually I just gave up trying to fix it and stopped using texture packs during that minecraft phase. I'm on a new one now with my new server I'm developing and ran into this issue again, except I'm pretty sure I found out what the problem is. MoreMcmeta and ETF/EMF were conflicting on textures causing models to break, so it was unrelated to this mod. It's just bizarre that having spartan shields installed seemed to be what triggered it. Modding is weird.
